Repository feedme-swent-epfl/feedme-android, pull requests merged in 2024-05, with the labels that each got.

#119 ViewModel for picture selection from Gallery
  app/src/androidTest/java/com/android/feedme/screen/FindRecipeScreen.kt
  app/src/androidTest/java/com/android/feedme/screen/GalleryScreen.kt
  app/src/androidTest/java/com/android/feedme/test/FindRecipeTest.kt
  app/src/androidTest/java/com/android/feedme/test/camera/GalleryTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/feedme/MainActivity.kt
  app/src/main/java/com/android/feedme/model/viewmodel/GalleryViewModel.kt
  app/src/main/java/com/android/feedme/ui/camera/Camera.kt
  app/src/main/java/com/android/feedme/ui/camera/Gallery.kt
  app/src/main/java/com/android/feedme/ui/find/FindRecipeScreen.kt
  app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/feedme/ui/theme/Color.kt
  app/src/main/res/drawable/camera.png
Labels: new

#125 Implement the GalleryScreen to display selected pictures
  app/src/androidTest/java/com/android/feedme/screen/GalleryScreen.kt
  app/src/androidTest/java/com/android/feedme/test/camera/GalleryTest.kt
  app/src/main/java/com/android/feedme/MainActivity.kt
  app/src/main/java/com/android/feedme/model/viewmodel/GalleryViewModel.kt
  app/src/main/java/com/android/feedme/ui/camera/Gallery.kt
Labels: new

#135 Store profile picture in Firestore
  .github/workflows/ci.yml
  app/build.gradle.kts
  app/src/androidTest/java/com/android/feedme/test/ui/EditProfileTest.kt
  app/src/main/java/com/android/feedme/model/data/ProfileRepository.kt
  app/src/main/java/com/android/feedme/model/viewmodel/GalleryViewModel.kt
  app/src/main/java/com/android/feedme/model/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/android/feedme/ui/camera/Gallery.kt
  app/src/main/java/com/android/feedme/ui/profile/EditProfileScreen.kt
  app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
  gradle/libs.versions.toml
Labels: new

#134 Implementing ViewModel Landing Page
  app/src/androidTest/java/com/android/feedme/test/LandingTest.kt
  app/src/main/java/com/android/feedme/MainActivity.kt
  app/src/main/java/com/android/feedme/model/data/RecipeRepository.kt
  app/src/main/java/com/android/feedme/model/viewmodel/LandingPageViewModel.kt
  app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
  app/src/test/java/com/android/feedme/ui/LandingViewModelTest.kt
Labels: help wanted

#237 Navigation bugs fix
  app/src/androidTest/java/com/android/feedme/test/LandingTest.kt
  app/src/androidTest/java/com/android/feedme/test/component/SmallThumbnailsDisplayTest.kt
  app/src/androidTest/java/com/android/feedme/test/ui/ProfileTest.kt
  app/src/main/java/com/android/feedme/MainActivity.kt
  app/src/main/java/com/android/feedme/model/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/android/feedme/model/viewmodel/RecipeViewModel.kt
  app/src/main/java/com/android/feedme/ui/component/RecipeFullDisplay.kt
  app/src/main/java/com/android/feedme/ui/component/SmallTumbnailsDisplay.kt
  app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
  app/src/main/java/com/android/feedme/ui/home/SavedRecipesScreen.kt
  app/src/main/java/com/android/feedme/ui/home/SearchScreen.kt
  app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
Labels: bug
