Repository feedme-swent-epfl/feedme-android, pull requests merged in 2024-04, with the labels that each got.

#33 APK building in Github Actions
  .github/workflows/apk.yml
Labels: setup

#48 Fix APK building
  .github/workflows/apk.yml
Labels: bug

#93 RecipeViewModel implementation
  app/src/androidTest/java/com/android/feedme/test/LandingTest.kt
  app/src/androidTest/java/com/android/feedme/test/ui/EditProfileTest.kt
  app/src/androidTest/java/com/android/feedme/test/ui/FullRecipeTest.kt
  app/src/androidTest/java/com/android/feedme/test/ui/ProfileTest.kt
  app/src/main/java/com/android/feedme/MainActivity.kt
  app/src/main/java/com/android/feedme/model/data/IngredientsRepository.kt
  app/src/main/java/com/android/feedme/model/data/RecipeRepository.kt
  app/src/main/java/com/android/feedme/model/viewmodel/AuthViewModel.kt
  app/src/main/java/com/android/feedme/model/viewmodel/CameraViewModel.kt
  app/src/main/java/com/android/feedme/model/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/android/feedme/model/viewmodel/RecipeViewModel.kt
  app/src/main/java/com/android/feedme/ui/auth/LoginScreen.kt
  app/src/main/java/com/android/feedme/ui/camera/Camera.kt
  app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
  app/src/main/java/com/android/feedme/ui/home/RecipeFullDisplay.kt
  app/src/main/java/com/android/feedme/ui/profile/EditProfileScreen.kt
  app/src/main/java/com/android/feedme/ui/profile/FriendsScreen.kt
  app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
  app/src/test/java/com/android/feedme/ui/AuthViewModelTest.kt
  app/src/test/java/com/android/feedme/ui/ProfileViewModelTest.kt
Labels: new

#112 SignOut button
  .gitignore
  app/src/androidTest/java/com/android/feedme/screen/SettingsScreen.kt
  app/src/androidTest/java/com/android/feedme/test/NotImplementedTest.kt
  app/src/androidTest/java/com/android/feedme/test/ui/SettingsTest.kt
  app/src/main/java/com/android/feedme/MainActivity.kt
  app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/feedme/ui/settings/SettingsScreen.kt
Labels: new

#113 Profile Navigation Bug
  app/src/main/java/com/android/feedme/model/viewmodel/ProfileViewModel.kt
Labels: bug

#103 Self sign APK
  .github/workflows/apk.yml
  .github/workflows/ci.yml
  .gitignore
  app/build.gradle.kts
Labels: bug
